### ISSUE TITLE
Valdis Story Abyssal City translate the game!

### ISSUE THREAD

**Issue by brtraducoes** [YAL-GameMaker-Tools/GmxDataSync#1]
Good Morning!
I went to test the tool in the game [Valdis Story Abyssal City], and does not extract displays an error message can help me with that I want to translate the game!
Original steam file!
http://prntscr.com/wonk1n
Thanks!

**Comment by YellowAfterlife** [comment]
This tool isn't made for translation at all - it extracts resource files on premise that you have a GMS1 project to insert them into.

* If you want to just extract all art assets, use [YYTextureView](https://yal.cc/r/17/yytextureview/) with show sprites ➜ extract sprites option.
* If you want to edit the game assets, use [UndertaleModTool](https://github.com/krzys-h/UndertaleModTool) or [TranslaTale](https://github.com/AlexWaveDiver/TranslaTale) (unsupported by now?)

**Comment by brtraducoes** [comment]
UndertaleModTool or TranslaTale are not compatible!
Can you help me?

**Comment by YellowAfterlife** [comment]
Given [how the past year went](https://yal.cc/2020-in-review/), I cannot currently invest days or weeks into making a new tool for translating a specific game - I already have a dozen things that I was supposed to finish a year ago.

Asking on [UTMT Discord server](https://discord.gg/RxXpdwJ) for possible alternatives would probably be your best bet.

**Comment by brtraducoes** [comment]
YYTextureView is perfect!
You can use it without being on the site!

**Comment by brtraducoes** [comment]
How much would you charge to make the tool to translate the game Valdis Story Abyssal City translate the game?
